import { Plus_Jakarta_Sans } from "next/font/google";import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";


export const metadata = {
  title: "Mobile App Devlopement Services",
  description: "Generated by create next app",
};

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jakarta", // This creates a CSS variable
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.variable} font-sans antialiased`}
      > <div className="min-h-screen bg-gray-50">
      <Header />
      <main>
        {children}
      </main>
    </div>
    <Footer/>
      </body>
    </html>
  );
}
